swagger: "2.0"
info:
  description: |
    Students - Classes Assignment RESTFul Web service.

    See [Gibhub Project](https://github.com/yassnet/student-class-assignment) for more information.
  version: "1.0"
  title: Students - Classes Assignment
  contact:
    name: yass.net@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
host: localhost:8080
basePath: /
schemes:
  - http
paths:
  /students:
    get:
      tags:
        - student
      summary: Get all students
      description: ""
      operationId: getAllStudents
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - firstName: query
          lastName: query
          key: query
          description: Find a student with a first name, last name or full name
      responses:
        "200":
          description: OK
        "405":
          description: Request method not supported
    delete:
      tags:
        - student
      summary: Deletes all students
      description: ""
      operationId: removeAll
      produces:
        - application/json
      responses:
        "204":
          description: OK
        "405":
          description: Request method not supported
    post:
      tags:
        - student
      summary: Create a new student
      description: ""
      operationId: saveStudent
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - fistName: body
          lastName: body
          description: Student object to be added to data base
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "201":
          description: Created
        "405":
          description: Request method not supported
  /students/{id}:
    put:
      tags:
        - student
      summary: Update an existing student
      description: ""
      operationId: updateStudent
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - fistName: body
          lastName: body
          description: Student object to be updated
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "200":
          description: OK
        "404":
          description: Student not found
        "405":
          description: Request method not supported
    get:
      tags:
        - student
      summary: Find student by ID
      description: Returns a student with Id
      operationId: findById
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Student not found
        "405":
          description: Request method not supported
    delete:
      tags:
        - student
      summary: Deletes a Student
      description: ""
      operationId: removeStudent
      produces:
        - application/json
      responses:
        "204":
          description: OK
        "404":
          description: Student not found
        "405":
          description: Request method not supported
  /classes:
    get:
      tags:
        - class
      summary: Get all classes
      description: ""
      operationId: getAllClasses
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - title: query
          description: query
          key: query
          description:  Find a class with a title, description or using a key (It finds in code, title and description)
      responses:
        "200":
          description: OK
        "405":
          description: Request method not supported
    delete:
      tags:
        - class
      summary: Deletes all classes
      description: ""
      operationId: removeAll
      produces:
        - application/json
      responses:
        "204":
          description: OK
        "405":
          description: Request method not supported
    post:
      tags:
        - class
      summary: Create a new class
      description: ""
      operationId: saveClass
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - code: body
          title: body
          description: body
          description: Class object to be added to data base
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "201":
          description: Created
        "405":
          description: Request method not supported
  /classes/{id}:
    put:
      tags:
        - class
      summary: Update an existing class
      description: ""
      operationId: updateClass
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - fistName: body
          lastName: body
          description: Class object to be updated
          required: true
          schema:
            $ref: "#/definitions/Class"
      responses:
        "200":
          description: OK
        "404":
          description: Class not found
        "405":
          description: Request method not supported
    get:
      tags:
        - class
      summary: Find class by ID
      description: Returns a class with Id
      operationId: findById
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Class not found
        "405":
          description: Request method not supported
    delete:
      tags:
        - class
      summary: Deletes a Class
      description: ""
      operationId: removeClass
      produces:
        - application/json
      responses:
        "204":
          description: OK
        "404":
          description: Class not found
        "405":
          description: Request method not supported
  /assignments:
    get:
      tags:
        - assignment
      summary: Get all assignments
      description: ""
      operationId: getAllAssignments
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "405":
          description: Request method not supported
    delete:
      tags:
        - assignment
      summary: Deletes a assignments
      description: ""
      operationId: removeAll
      produces:
        - application/json
      responses:
        "204":
          description: OK
        "405":
          description: Request method not supported
  /classes/{code}/students:
    get:
      tags:
        - assignment
      summary: Get all students of a class
      description: ""
      operationId: findByClass
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "405":
          description: Request method not supported
  /students/{code}/classes:
    get:
      tags:
        - assignment
      summary: Get all classes of a student
      description: ""
      operationId: findByClass
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "405":
          description: Request method not supported
  /classes/{code}/students/{id}:
    put:
      tags:
        - assignment
      summary: Assign a class to student
      description: ""
      operationId: assign
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Class or Student not found
        "405":
          description: Request method not supported
    delete:
      tags:
        - assignment
      summary: Deletes a Student of a Class
      description: ""
      operationId: removeAssignment
      produces:
        - application/json
      responses:
        "204":
          description: OK
        "404":
          description: Class or Student not found
        "405":
          description: Request method not supported
  /students/{code}/classes/{id}:
    put:
      tags:
        - assignment
      summary: Assign a student to class
      description: ""
      operationId: assign
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Class or Student not found
        "405":
          description: Request method not supported
    delete:
      tags:
        - assignment
      summary: Deletes a Class of a Student
      description: ""
      operationId: removeAssignment
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Class or Student not found
        "405":
          description: Request method not supported
definitions:
  Student:
    type: object
    required:
      - firstName
      - lastName
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
  Class:
    type: object
    required:
      - code
    properties:
      code:
        type: string
      title:
        type: string
      description:
        type: string
  StudentClass:
    type: object
    required:
      - student
      - class
    properties:
      student:
        type: object
      class:
        type: object